### ISSUE TITLE
missing parent/parent: accessors in XMLNode

### ISSUE THREAD

**Issue by pmon** [pbella/Cuis-Ports#1]
Hi Phil, I am using XMLWriter class and after loading the latest XMLParser package I am reporting errors while creating an XMLElement explicitly using

XMLElement named: 'whatever' .

I was able to fix this and another similar issue implementing parent and parent: accessors in class XMLNode.
Hope this can help

**Comment by pbella** [comment]
Just an update in case you are still using the XMLParser package from this repo: it has been deprecated (I have switched to the Cuis core XML package with relatively minimal changes required and the added advantage of having more people working with/on that XML package.)  All of the other packages in this repo, including XPath, continue to be maintained.
